#!/usr/bin/env python3
"""Regenerate pokeldn/frlg/rom/special_names.py from the decompilation.

The index is the special [decomp:src/scrcmd.c:101], so the decomp's order names a dumped address.

    ./.venv/bin/python scripts/gen_special_names.py [~/pokefirered]
"""
import pathlib
import re
import sys

DECOMP = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "~/pokefirered").expanduser()
OUT = pathlib.Path(__file__).resolve().parent.parent / "pokeldn" / "frlg" / "rom" / "special_names.py"

HEADER = '''"""The 444 entries of `gSpecials`, in table order [decomp:data/specials.inc].

The index IS the special: `ScrCmd_special` reads a u16, bounds-checks `&gSpecials[i]` against
`gSpecialsEnd` and calls through it [decomp:src/scrcmd.c:101]. Generated by
scripts/gen_special_names.py; the names are the decomp's own.

The table's address needed no search: ScrCmd_special's own literal pool holds 0x081639FC and 0x081640EC
out of its literal pool, and 0x081640EC - 0x081639FC is 0x6F0 = 444 * 4, which is the length of
this list. It also lands immediately after gSpecialVars (0x081639A8 + 21 * 4), which is the order
ld_script puts them in. docs/frlg_rom.md.

MANY ENTRIES SHARE A FUNCTION. `NullFieldSpecial` appears dozens of times, so a dump of the table
proves its own alignment: those indices must all come back with ONE address.
"""

SPECIALS = (
'''


def main():
    source = (DECOMP / "data" / "specials.inc").read_text()
    body = source.split("gSpecials::", 1)[1].split("gSpecialsEnd::", 1)[0]
    names = re.findall(r"^\s*def_special\s+(\w+)", body, re.M)
    if not names:
        raise SystemExit("no def_special entries found; is that a FRLG decomp?")
    lines = [HEADER]
    for index in range(0, len(names), 3):
        lines.append("    " + " ".join(f"{n!r}," for n in names[index:index + 3]))
    lines.append(")")
    lines.append("")
    lines.append("SPECIAL_COUNT = len(SPECIALS)")
    lines.append("SPECIALS_TABLE_SIZE = SPECIAL_COUNT * 4")
    lines.append('''

def read_table(dump, base, first=0):
    """-> [(index, name, address, thumb_bit)] for a dump of gSpecials at `base` starting at
    entry `first`. A dump is at most 256 entries, so `first` is how the rest is read."""
    out = []
    for i in range(min(SPECIAL_COUNT - first, len(dump) // 4)):
        value = int.from_bytes(bytes(dump[4 * i:4 * i + 4]), "little")
        out.append((first + i, SPECIALS[first + i], value & ~1, bool(value & 1)))
    return out


def index(name):
    """-> the index of a special by the decomp's name. Raises if the name is used more than once,
    because then the caller has to say WHICH one."""
    hits = [i for i, known in enumerate(SPECIALS) if known == name]
    if not hits:
        raise KeyError(f"{name!r} is not in gSpecials")
    if len(hits) > 1:
        raise KeyError(f"{name!r} appears at {len(hits)} indices: {hits}")
    return hits[0]''')
    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT} ({len(names)} specials)")


if __name__ == "__main__":
    main()
