#!/usr/bin/env python3
"""Assemble every asm/resident/*.s into pokeldn/frlg/rom/resident_stubs.py.

A third kind of payload, and the distinction matters. A buffer script (`asm/*.s`) is called once
per frame by the Mystery Gift client and stops when the session does. A field stub (`asm/field/*.s`)
is staged by a RAM script and runs once, in the overworld, when the player talks to an object. A
resident stub is neither: it is written into the top of EWRAM and installed in `gIntrTable`, and it
runs every frame afterwards in every game state [docs/frlg_rom.md, Code that outlives the session].

It is never executed where it is assembled, so it is stored as words. Whatever installs it writes
those words somewhere and patches the two addresses it needs, which is why the symbol offsets are
recorded here the way the field generator records them.

The committed bytes are the source of truth at run time: a live host must not need a GBA toolchain.
`tests/test_resident_stubs.py` re-assembles and compares whenever arm-none-eabi-as is installed.

    ./scripts/gen_resident_stubs.py [--check]
"""

import argparse
import hashlib
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "scripts"))

from gen_field_stubs import AS, assemble  # noqa: E402

ASM_DIR = ROOT / "asm" / "resident"
OUT = ROOT / "pokeldn" / "frlg" / "rom" / "resident_stubs.py"


def render():
    lines = [
        '"""Generated by scripts/gen_resident_stubs.py from asm/resident/*.s. '
        'Do not edit by hand."""',
        "",
        "# name -> (THUMB machine code, sha256 of the asm source, {symbol: byte offset})",
        "STUBS = {",
    ]
    for source in sorted(ASM_DIR.glob("*.s")):
        code, symbols = assemble(source)
        if len(code) % 4:
            raise SystemExit(f"{source.name}: {len(code)} bytes is not a whole number of words, "
                             f"and an installer writes words")
        digest = hashlib.sha256(source.read_bytes()).hexdigest()
        lines.append(f"    {source.stem!r}: (")
        lines.append(f"        bytes.fromhex({code.hex()!r}),")
        lines.append(f"        {digest!r},")
        lines.append(f"        {dict(sorted(symbols.items()))!r},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the committed module is stale")
    args = parser.parse_args()
    try:
        rendered = render()
    except FileNotFoundError:
        print(f"{AS} is not installed; nothing to check", file=sys.stderr)
        return 0
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            print(f"{OUT} is stale; run ./scripts/gen_resident_stubs.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
