#!/usr/bin/env python3
"""Regenerate pokeldn/bdsp/netdata.py from a TeamLumi/opendpr checkout.

    ./.venv/bin/python scripts/gen_bdsp_netdata.py [~/opendpr] [--check]

`--check` diffs instead of writing. The layout is packed: a console's NetJoinData is 17 bytes with
`short InitRotY` at offset 3.
"""
import pathlib
import re
import sys

# C# type -> (struct format, size). Anything else makes a payload UNKNOWN rather than a guess.
PRIMITIVES = {
    "byte": ("B", 1), "sbyte": ("b", 1), "bool": ("?", 1),
    "short": ("h", 2), "ushort": ("H", 2),
    "int": ("i", 4), "uint": ("I", 4), "float": ("f", 4),
    "long": ("q", 8), "ulong": ("Q", 8), "double": ("d", 8),
    "Vector2": ("2f", 8), "Vector3": ("3f", 12), "Vector2Int": ("2i", 8), "Vector3Int": ("3i", 12),
}

FIELD = re.compile(r"^\s*public\s+([\w.<>\[\]]+)\s+(\w+)\s*;", re.M)
STRUCT = re.compile(r"public\s+struct\s+(\w+)\s*\{(.*?)\n\}", re.S)
ENUM = re.compile(r"public\s+enum\s+(\w+)\s*:\s*(\w+)")
DATA_ID = re.compile(r"static\s+byte\s+DataID\s*\{\s*get\s*=>\s*(\d+)\s*;")
PAYLOAD_TYPE = re.compile(r"ANetData<(\w+)>")


def scan(root):
    """-> (structs, enums), every one in the checkout, by name."""
    structs, enums = {}, {}
    for path in sorted(root.rglob("*.cs")):
        text = path.read_text(encoding="utf-8-sig", errors="replace")
        for name, body in STRUCT.findall(text):
            structs.setdefault(name, FIELD.findall(body))
        for name, base in ENUM.findall(text):
            enums.setdefault(name, base)
    return structs, enums


def flatten(type_name, structs, enums, seen=()):
    """-> [(path, csharp type, format)] for a payload struct, or None if anything is not blittable.
    A nested struct is inlined; one that reaches itself has no fixed size."""
    if type_name in enums:
        fmt = PRIMITIVES.get(enums[type_name])
        return [((), type_name, fmt[0])] if fmt else None
    if type_name in PRIMITIVES:
        return [((), type_name, PRIMITIVES[type_name][0])]
    if type_name not in structs or type_name in seen:
        return None
    out = []
    for ctype, cname in structs[type_name]:
        inner = flatten(ctype, structs, enums, seen + (type_name,))
        if inner is None:
            return None
        out.extend(((cname,) + path, t, f) for path, t, f in inner)
    return out


def collect(root):
    """-> [(data_id, class name, payload struct, fields or None)], in id order."""
    netutils = root / "Assets" / "Scripts" / "Dpr" / "NetworkUtils"
    if not netutils.is_dir():
        raise SystemExit(f"not an opendpr checkout: {netutils} does not exist")
    structs, enums = scan(root / "Assets" / "Scripts")
    rows = []
    for path in sorted(netutils.glob("Net*.cs")):
        text = path.read_text(encoding="utf-8-sig", errors="replace")
        ident, payload = DATA_ID.search(text), PAYLOAD_TYPE.search(text)
        if not ident or not payload:
            continue
        rows.append((int(ident.group(1)), path.stem, payload.group(1),
                     flatten(payload.group(1), structs, enums)))
    return sorted(rows)


HEADER = '''"""Every message BDSP's own protocol carries, by data id [opendpr:Dpr/NetworkUtils].

Generated by scripts/gen_bdsp_netdata.py from a TeamLumi/opendpr checkout. `NetDataParser` registers
one `ANetData<T>` per message, each declaring its own `DataID` byte and one plain struct `T`, so
none of this was read off a capture and none of it is a guess. `pokeldn.bdsp.room` is what encodes
and decodes; this is only the table.

THE IDS ARE NIBBLE-GROUPED - 0x01..0x09, 0x10..0x19, 0x20..0x29, and so on, no low nibble ever
reaching 0xA - so a gap in the numbering is the grouping and not a message this table is missing.

FIELDS is the packed layout, and PACKED is measured, not assumed: a real console's NetJoinData is
17 bytes with `short InitRotY` at offset 3, where C#'s default alignment would put it at 4 and make
the message 20. A payload whose struct holds a string, an array or a list has NO entry here - its
layout is not decidable from the source, and inventing one is what this file exists to prevent.

Each FIELDS entry is (name, C# type, struct format); a nested struct is inlined under a dotted name,
because the wire carries fields and not structs.
"""
'''


def render(rows):
    out = [HEADER, "", "NAMES = {"]
    for ident, cls, payload, _ in rows:
        out.append(f"    {ident:#04x}: ({cls!r}, {payload!r}),")
    out += ["}", "", "", "# The packed layout of every payload whose struct is entirely blittable.",
            "FIELDS = {"]
    for ident, cls, _, fields in rows:
        if fields is None:
            continue
        out.append(f"    {ident:#04x}: (   # {cls}")
        for path, ctype, fmt in fields:
            out.append(f"        ({'.'.join(path)!r}, {ctype!r}, {fmt!r}),")
        out.append("    ),")
    out += ["}", "", "",
            "# The payloads whose struct is not blittable - a string, an array or a list. The id and",
            "# the name are known; the layout is not, and must be measured before it is written down.",
            "OPAQUE = {"]
    for ident, cls, payload, fields in rows:
        if fields is None:
            out.append(f"    {ident:#04x}: {payload!r},   # {cls}")
    out.append("}")
    return "\n".join(out) + "\n"


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("--")]
    root = pathlib.Path(args[0] if args else "~/opendpr").expanduser()
    out = pathlib.Path(__file__).resolve().parent.parent / "pokeldn" / "bdsp" / "netdata.py"
    text = render(collect(root))
    if "--check" in sys.argv[1:]:
        have = out.read_text() if out.exists() else ""
        if have != text:
            print(f"{out} is NOT what the checkout generates")
            return 1
        print(f"{out} matches the checkout")
        return 0
    out.write_text(text)
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
