#!/usr/bin/env python3
"""Regenerate pokeldn/frlg/text/easychat_values.py from the decompilation.

IsECWordInvalid checks species and move words against value lists [decomp:src/easy_chat.c:129];
these are the lists.

    ./.venv/bin/python scripts/gen_easychat_values.py [~/pokefirered]
"""
import pathlib
import re
import sys

DECOMP = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else "~/pokefirered").expanduser()
OUT = pathlib.Path(__file__).resolve().parent.parent / "pokeldn" / "frlg" / "text" / "easychat_values.py"

GROUPS = (
    ("POKEMON_VALUES", "easy_chat_group_pokemon.h", "SPECIES_", "include/constants/species.h"),
    ("POKEMON_2_VALUES", "easy_chat_group_pokemon2.h", "SPECIES_", "include/constants/species.h"),
    ("MOVE_1_VALUES", "easy_chat_group_move_1.h", "MOVE_", "include/constants/moves.h"),
    ("MOVE_2_VALUES", "easy_chat_group_move_2.h", "MOVE_", "include/constants/moves.h"),
)

HEADER = '''"""The Easy Chat words that are the SAME word in every language.

`CopyEasyChatWord` prints most groups out of `sEasyChatGroups[group].wordData.words[index].text` -
a per-language table the English decompilation says nothing about. Four groups are the exception
[decomp:src/easy_chat.c:155]:

    case EC_GROUP_POKEMON:
    case EC_GROUP_POKEMON_2:
        return gSpeciesNames[index];
    case EC_GROUP_MOVE_1:
    case EC_GROUP_MOVE_2:
        return gMoveNames[index];

The index IS the species number or the move id, and the console prints it from its own localized
name table. A species word is therefore the right word in every language by construction - the only
part of the Easy Chat vocabulary that needs no verification on hardware.

Confirmed on a French console: the player typed AKWAKWAK and POKEMON/55 came back, and
SPECIES_GOLDUCK is 55; they typed AEROBLAST and MOVE_1/177 came back, and MOVE_AEROBLAST is 177.

`IsECWordInvalid` checks the index against the group's value list rather than a count
[decomp:src/easy_chat.c:129], so not every species or move is a legal word. These are the lists.
Generated by scripts/gen_easychat_values.py; do not edit by hand.
"""

'''


def constants(path, prefix):
    out = {}
    for line in (DECOMP / path).read_text().splitlines():
        match = re.match(rf"#define {prefix}(\w+)\s+(\d+)", line)
        if match:
            out[match.group(1)] = int(match.group(2))
    return out


def emit(name, values):
    rows = [values[i:i + 16] for i in range(0, len(values), 16)]
    body = "\n".join("    " + " ".join(f"{v}," for v in row) for row in rows)
    return f"{name} = frozenset((\n{body}\n))\n"


def main():
    parts = [HEADER]
    for name, filename, prefix, constants_path in GROUPS:
        table = constants(constants_path, prefix)
        text = (DECOMP / "src/data/easy_chat" / filename).read_text()
        names = re.findall(rf"\b{prefix}(\w+)\b", text)
        unknown = sorted({n for n in names if n not in table})
        if unknown:
            raise SystemExit(f"{filename}: unknown {prefix} constants {unknown}")
        parts.append(emit(name, sorted({table[n] for n in names})))
    parts.append(
        '\n__all__ = ["MOVE_1_VALUES", "MOVE_2_VALUES", "POKEMON_2_VALUES", "POKEMON_VALUES"]\n')
    OUT.write_text("\n".join(parts))
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
