#!/usr/bin/env python3
"""Generate the shipped Gen III name table from an explicit species.h path."""
import argparse
import re
from pathlib import Path


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("header", type=Path)
    parser.add_argument("--output", type=Path, default=Path(__file__).resolve().parents[1] /
                        "pokeldn/frlg/save/species_names.py")
    args = parser.parse_args()
    names = {}
    for name, number in re.findall(r"^#define SPECIES_(\w+)\s+(\d+)", args.header.read_text(), re.M):
        names.setdefault(int(number), name)
    args.output.write_text('"""Gen III internal species names, generated by scripts/gen_species_names.py."""\n\n'
                          + 'SPECIES = {\n' + ''.join(f'    {number}: {name!r},\n' for number, name in sorted(names.items())) + '}\n')


if __name__ == "__main__":
    main()
