#!/usr/bin/env python3
"""Assemble every asm/field/*.s into pokeldn/frlg/rom/field_stubs.py.

    ./scripts/gen_field_stubs.py [--check]

Field stubs live outside `asm/`, which gen_buffer_scripts.py globs: a RAM script stages them and
reaches them with `callnative` [pokeldn/frlg/rom/native_script.py]. Symbol offsets are recorded
because the parameters sit in a literal pool after the code, where no fixed offset reaches.
"""

import argparse
import hashlib
import pathlib
import subprocess
import sys
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
ASM_DIR = ROOT / "asm" / "field"
OUT = ROOT / "pokeldn" / "frlg" / "rom" / "field_stubs.py"

AS = "arm-none-eabi-as"
OBJCOPY = "arm-none-eabi-objcopy"
NM = "arm-none-eabi-nm"
AS_FLAGS = ["-march=armv4t", "-mcpu=arm7tdmi"]


def assemble(source_path):
    """-> (raw thumb bytes, {global symbol: byte offset}). No toolchain raises FileNotFoundError."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp = pathlib.Path(tmp)
        obj, binary = tmp / "a.o", tmp / "a.bin"
        subprocess.run([AS, *AS_FLAGS, "-I", str(pathlib.Path(source_path).parent), "-o", str(obj),
                        str(source_path)], check=True)
        subprocess.run([OBJCOPY, "-O", "binary", str(obj), str(binary)], check=True)
        listing = subprocess.run([NM, "--defined-only", str(obj)],
                                 check=True, capture_output=True, text=True).stdout
        symbols = {}
        for line in listing.splitlines():
            value, _kind, name = line.split()
            symbols[name] = int(value, 16)
        return binary.read_bytes(), symbols


def render():
    lines = [
        '"""Generated by scripts/gen_field_stubs.py from asm/field/*.s. Do not edit by hand."""',
        "",
        "# name -> (THUMB machine code, sha256 of the asm source, {symbol: byte offset})",
        "STUBS = {",
    ]
    for source in sorted(ASM_DIR.glob("*.s")):
        code, symbols = assemble(source)
        digest = hashlib.sha256(source.read_bytes()).hexdigest()
        lines.append(f"    {source.stem!r}: (")
        lines.append(f"        bytes.fromhex({code.hex()!r}),")
        lines.append(f"        {digest!r},")
        lines.append(f"        {dict(sorted(symbols.items()))!r},")
        lines.append("    ),")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if the committed module is stale")
    args = parser.parse_args()
    try:
        rendered = render()
    except FileNotFoundError:
        print(f"{AS} is not installed; nothing to check", file=sys.stderr)
        return 0
    if args.check:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != rendered:
            print(f"{OUT} is stale; run ./scripts/gen_field_stubs.py", file=sys.stderr)
            return 1
        return 0
    OUT.write_text(rendered, encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
