#!/usr/bin/env python3
"""Regenerate pokeldn/frlg/rom/worker_names.py: the workers behind the tables, named without a run.

    ./.venv/bin/python scripts/gen_worker_names.py [~/pokefirered] [--report] [--check]

FireRed's dumps only: an image of both cartridges answers with whichever it placed at an address.
The four checks: docs/frlg_rom_map.md, Naming 300 workers offline.
"""
import argparse
import collections
import os
import pathlib
import re
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
# tools/frlg, not tools/. conftest.py hides a wrong path from the suite; the guard is
# test_documentation's standalone check over scripts/.
sys.path.insert(0, os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
                                "tools", "frlg"))

from pokeldn.frlg.rom import decomp_source, rom_map, scrcmd, thumb  # noqa: E402
from rom_functions import deduplicate, known_names, tables              # noqa: E402
from script_read import every_dump                                      # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUT = ROOT / "pokeldn" / "frlg" / "rom" / "worker_names.py"
ROM_START, ROM_END = 0x08000000, 0x0A000000
ADDRESS = 2

# rom_map constants that are a limit rather than a name for the code at that address.
# SHARED_WITH_LEAFGREEN_THROUGH sits on 0x0807AF04, which is also the highest call target that did
# not move between the cartridges: a function, and one this method can name.
MARKERS = frozenset({"SHARED_WITH_LEAFGREEN_THROUGH"})


def link_order(decomp):
    """-> {source file: its place in the ROM}, from ld_script_rev10.ld's .text list."""
    text = (decomp / "ld_script_rev10.ld").read_text()
    body = text.split(".text", 1)[1]
    body = body[:body.index("} >")] if "} >" in body else body
    order = {}
    for match in re.finditer(r"src/([A-Za-z0-9_]+)\.o\(\.text", body):
        order.setdefault(match.group(1) + ".c", len(order))
    return order

HEADER = '''"""The workers behind the four function tables, named from the decomp WITHOUT a run.

Generated by scripts/gen_worker_names.py; do not edit by hand. Every name here is one the console's
own code proved: the body of a table entry this project can name, dumped off the cartridge, calls
these addresses in the order the decompilation's source for that same function calls them.

Four checks decide whether a name lands in this file - an equal number of calls on both sides, every
already-measured address landing back on its own name, every caller of an address agreeing, and one
file's names coming back in the order the file defines them. The generator's docstring has the
detail and `--report` prints what was dropped.

WHAT THIS IS NOT: a call target. `rom_map.CALLABLE` is the list of functions this project has CALLED
on the console, each one measured by a run that did something visible. A name here is a reading, and
a reading that has held up across every body that reaches the address - but the first time one of
them is called, that call is the measurement.
"""
'''


def measured_bodies(memory, entries):
    """-> [(label, address, [bl targets])] for the table entries the dumps hold.

    Bounded by the next entry AND the epilogue: a function with two returns swallows its neighbour."""
    held = [(label, address) for label, address in entries if address in memory]
    starts = sorted(address for _label, address in held)
    out = []
    for label, address in sorted(held, key=lambda entry: entry[1]):
        base, data = memory.segment(address)
        after = [start for start in starts if start > address] + [base + len(data)]
        end = thumb.function_end(data, base, address, min(after[0], base + len(data)))
        out.append((label, address, [target & ~1
                                     for _site, target in thumb.bl_targets(data, base, address, end)
                                     if ROM_START <= target < ROM_END]))
    return out


def normalise(name):
    """-> a name with the shape taken out of it, so SCRIPT_READ_WORD and ScriptReadWord meet."""
    return name.replace("_", "").lower()


def same_function(ours, theirs):
    """-> whether our name and the decomp's are one function. An UPPER_SNAKE name we coined matches by
    shape; anything else exactly: `gMysteryEventScriptCmdTable` holds opcode names, and
    `enableresetrtc` is not `EnableResetRTC`."""
    if ours.isupper():
        return normalise(ours) == normalise(theirs)
    return ours == theirs


def decomp_name(ours, source_names):
    """-> the decomp's name for what this project calls `ours`, or None if it names nothing there."""
    if ours in source_names:
        return ours
    if ours.isupper():
        folded = normalise(ours)
        for name in source_names:
            if normalise(name) == folded:
                return name
    return None


def entry_name(label):
    """-> the function name inside a table label: `ScrCmd_end [2]`, `NullFieldSpecial x171`."""
    return label.split(" [")[0].split(" x")[0]


def anchor_pairs(measured_names, source):
    """-> [(i, j)] where a target we already name meets its name in source; an LCS, so a function
    called twice cannot pull the alignment sideways."""
    n, m = len(measured_names), len(source)
    best = [[0] * (m + 1) for _ in range(n + 1)]
    for i in range(n - 1, -1, -1):
        for j in range(m - 1, -1, -1):
            if measured_names[i] is not None and measured_names[i] == source[j]:
                best[i][j] = best[i + 1][j + 1] + 1
            else:
                best[i][j] = max(best[i + 1][j], best[i][j + 1])
    out, i, j = [], 0, 0
    while i < n and j < m:
        if measured_names[i] is not None and measured_names[i] == source[j]:
            out.append((i, j))
            i, j = i + 1, j + 1
        elif best[i + 1][j] >= best[i][j + 1]:
            i += 1
        else:
            j += 1
    return out


def closed_gaps(measured, source, names, source_names):
    """-> [(address, name)] forced by a closed gap: one unnamed target and one call between anchors."""
    measured_names = [decomp_name(names[target], source_names) if target in names else None
                      for target in measured]
    pairs, out = anchor_pairs(measured_names, source), []
    for (first_measured, first_source), (next_measured, next_source) in zip(pairs, pairs[1:]):
        gap_measured = measured[first_measured + 1:next_measured]
        gap_source = source[first_source + 1:next_source]
        if len(gap_measured) == len(gap_source) == 1 and gap_source[0] != decomp_source.INDIRECT \
                and gap_measured[0] not in names:
            out.append((gap_measured[0], gap_source[0]))
    return out


def align(decomp_calls, memory, names, source_names):
    """-> (proposals, corrections, dropped) from every body the dumps hold.

    `proposals` is {address: {name: [callers]}} - a second name for an address is a contradiction
    and the caller resolves it by dropping the address. `corrections` is the other direction: an
    address this project named itself, in a slot where the decomp names a function it knows."""
    proposals = collections.defaultdict(lambda: collections.defaultdict(list))
    corrections, dropped = collections.defaultdict(set), collections.Counter()
    for group, entries in tables().items():
        for label, _address, measured in measured_bodies(memory, deduplicate(entries)):
            name = entry_name(label)
            if name not in decomp_calls:
                dropped["no source for the entry"] += 1
                continue
            source = decomp_calls[name]
            if len(measured) != len(source):
                forced = closed_gaps(measured, source, names, source_names)
                dropped["call count differs, an anchored gap named one" if forced
                        else "call count differs"] += 1
                for target, called in forced:
                    proposals[target][called].append((name, len(measured)))
                continue
            pairs, anchors, bad = [], 0, False
            for target, called in zip(measured, source):
                if called == decomp_source.INDIRECT:
                    continue
                known = names.get(target)
                if known is None:
                    pairs.append((target, called))
                elif same_function(known, called):
                    anchors += 1
                elif decomp_name(known, source_names):
                    bad = True                      # both names are the decomp's: a real conflict
                    break
                elif called in source_names:
                    corrections[target].add((known, called, name))
            if bad:
                dropped["a measured name did not match"] += 1
                continue
            dropped["named" if pairs else "nothing new"] += 1
            for target, called in pairs:
                proposals[target][called].append((name, anchors))
    return proposals, corrections, dropped


def resolve(proposals, where, names, link_order):
    """-> ({address: name}, [rejection]) after agreement, uniqueness and definition order."""
    rejected, accepted = [], {}
    by_name = collections.defaultdict(set)
    for address, options in proposals.items():
        if len(options) > 1:
            rejected.append(f"0x{address:08X}: callers disagree - " + ", ".join(sorted(options)))
            continue
        name = next(iter(options))
        if name not in where:
            rejected.append(f"0x{address:08X}: {name} is not a function in the decomp's C sources")
            continue
        accepted[address] = name
        by_name[name].add(address)
    for name, addresses in by_name.items():
        if len(addresses) > 1:
            rejected.append(f"{name}: proposed at " + ", ".join(f"0x{a:08X}" for a in
                                                                sorted(addresses)))
            for address in addresses:
                accepted.pop(address, None)

    # Link order [ld_script_rev10.ld:53]: the longest ascending chain wins, not the first break, or
    # one misplaced name rejects every one after it. docs/frlg_rom_map.md
    known_by_name = {}
    for address, label in names.items():
        name = decomp_name(entry_name(label), set(where))
        if name:
            known_by_name.setdefault(name, address)
    points = []
    for address, name in accepted.items():
        source_file, index = where[name]
        points.append((link_order.get(source_file, len(link_order)), index, address, name, True))
    for name, (source_file, index) in where.items():
        address = known_by_name.get(name)
        if address is not None and source_file in link_order:
            points.append((link_order[source_file], index, address, name, False))
    for _object, _index, address, name, proposed in ascending_outliers(sorted(points)):
        if proposed:
            rejected.append(f"{name}: 0x{address:08X} breaks the link order")
            accepted.pop(address, None)
        else:
            rejected.append(f"{name}: 0x{address:08X} is MEASURED and breaks the link order - "
                            f"one of the two readings is wrong")
    return accepted, rejected


def ascending_outliers(points):
    """-> the points outside the longest ascending-by-address chain, in link order."""
    best = [1] * len(points)
    previous = [-1] * len(points)
    for i in range(len(points)):
        for j in range(i):
            if points[j][ADDRESS] < points[i][ADDRESS] and best[j] + 1 > best[i]:
                best[i], previous[i] = best[j] + 1, j
    if not points:
        return []
    end = max(range(len(points)), key=lambda i: best[i])
    keep, cursor = set(), end
    while cursor >= 0:
        keep.add(cursor)
        cursor = previous[cursor]
    return [point for index, point in enumerate(points) if index not in keep]


def render(accepted, where, proposals):
    lines = [HEADER, "", "WORKERS = {"]
    for address in sorted(accepted):
        name = accepted[address]
        callers = sorted({caller for caller, _anchors in proposals[address][name]})
        note = callers[0] if len(callers) == 1 else f"{callers[0]} +{len(callers) - 1}"
        lines.append(f"    0x{address:08X}: {name!r},".ljust(60) + f"# {note}")
    lines.append("}")
    lines.append("")
    lines.append("# Where the decomp defines each one, and how many of the table's bodies reached")
    lines.append("# it. A worker with several callers is one several bodies agreed about.")
    lines.append("SOURCES = {")
    for address in sorted(accepted):
        name = accepted[address]
        source_file, index = where[name]
        callers = len({caller for caller, _anchors in proposals[address][name]})
        lines.append(f"    {name!r}: ({source_file!r}, {index}, {callers}),")
    lines.append("}")
    lines.append("")
    lines.append("WORKER_ADDRESSES = {name: address for address, name in WORKERS.items()}")
    lines.append("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("decomp", nargs="?", default="~/pokefirered")
    ap.add_argument("--scratchpad", default=str(ROOT / "scratchpad"))
    ap.add_argument("--console", default="firered")
    ap.add_argument("--report", action="store_true", help="what was dropped, and why")
    ap.add_argument("--check", action="store_true", help="write nothing; fail if the module differs")
    args = ap.parse_args()

    decomp = pathlib.Path(args.decomp).expanduser()
    sources = sorted(decomp.glob("src/**/*.c"))
    if not sources:
        raise SystemExit(f"no C sources under {decomp}; is that a pokefirered checkout?")
    decomp_calls, where = decomp_source.read_tree(sources)
    source_names = set(where)

    segments = every_dump(args.scratchpad, args.console)
    if not segments:
        raise SystemExit(f"no {args.console} dumps under {args.scratchpad}")
    memory = scrcmd.Memory(segments)
    names = {address: entry_name(label)
             # with_english=False: a name deduced from the English build must not anchor the next.
             for address, label in known_names(with_workers=False, with_english=False).items()
             if entry_name(label) not in MARKERS}
    names.update(rom_map.DECOMP_NAMES)

    proposals, corrections, dropped = align(decomp_calls, memory, names, source_names)
    accepted, rejected = resolve(proposals, where, names, link_order(decomp))
    text = render(accepted, where, proposals)

    if args.report:
        print(f"{len(decomp_calls)} functions read from {len(sources)} sources, "
              f"{len(memory)} bytes of {args.console} in {len(memory.segments)} region(s)")
        for reason, count in dropped.most_common():
            print(f"  {count:4d} bodies: {reason}")
        print(f"\n  {len(accepted)} workers named, {len(rejected)} address(es) rejected")
        for line in rejected:
            print(f"    {line}")
        if corrections:
            print("\n  names this project coined where the decomp has one of its own:")
            for address, entries in sorted(corrections.items()):
                for ours, theirs, caller in sorted(entries):
                    print(f"    0x{address:08X}  {ours} -> {theirs}   (from {caller})")

    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if current != text:
            raise SystemExit("pokeldn/frlg/rom/worker_names.py is not what this decomp and these dumps say; "
                             "rerun scripts/gen_worker_names.py")
        print(f"pokeldn/frlg/rom/worker_names.py matches: {len(accepted)} workers")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(ROOT)}: {len(accepted)} workers named, "
          f"{len(rejected)} rejected")


if __name__ == "__main__":
    main()
