"""Seed-to-encounter and seed-to-reward data for Scarlet/Violet Tera raids.

The bundled catalog is generated by ``tools/sv/import_raid_data.py`` from the GPLv3 Tera Finder
and PKHeX resources.  This module contains the small deterministic selection and lottery layer;
it deliberately has no transport or replay dependency.
"""

from __future__ import annotations

import base64
from functools import lru_cache
import json
from pathlib import Path
import struct

from pokeldn.sv.raid_generation import Xoroshiro128Plus


DATA_PATH = Path(__file__).with_name("data") / "raid_base.json"
PERSONAL_SIZE = 0x50

RATE_TOTALS = {
    ("paldea", "scarlet"): (0, 5800, 5300, 7400, 8800, 9100, 6500),
    ("paldea", "violet"): (0, 5800, 5300, 7400, 8700, 9100, 6500),
    ("kitakami", "scarlet"): (0, 1500, 1500, 2500, 2100, 2250, 2475),
    ("kitakami", "violet"): (0, 1500, 1500, 2500, 2100, 2250, 2574),
    ("blueberry", "scarlet"): (0, 1100, 1100, 2000, 1900, 2100, 2600),
    ("blueberry", "violet"): (0, 1100, 1100, 2000, 1900, 2100, 2600),
}

REWARD_SLOTS = (
    (4, 5, 6, 7, 8),
    (4, 5, 6, 7, 8),
    (5, 6, 7, 8, 9),
    (5, 6, 7, 8, 9),
    (6, 7, 8, 9, 10),
    (7, 8, 9, 10, 11),
    (7, 8, 9, 10, 11),
)

TERA_SHARDS = (1862, 1868, 1871, 1869, 1870, 1874, 1873, 1875, 1878,
               1863, 1864, 1866, 1865, 1872, 1867, 1876, 1877, 1879)


@lru_cache(maxsize=1)
def load_catalog(path: str | Path = DATA_PATH) -> dict:
    with open(path, encoding="utf-8") as source:
        data = json.load(source)
    data["personal_sv"] = base64.b64decode(data["personal_sv"])
    return data


def _stars(rand: Xoroshiro128Plus, progress: str) -> int:
    roll = rand.next_int(100)
    if progress == "6star":
        return 5 if roll > 70 else 4 if roll > 30 else 3
    if progress == "5star":
        return 5 if roll > 75 else 4 if roll > 40 else 3
    if progress == "4star":
        return 4 if roll > 70 else 3 if roll > 40 else 2 if roll > 20 else 1
    if progress == "3star":
        return 3 if roll > 70 else 2 if roll > 30 else 1
    if progress in ("beginning", "tera"):
        return 2 if roll > 80 else 1
    raise ValueError(f"unknown game progress {progress!r}")


def select_encounter(seed: int, *, version: str = "violet", progress: str = "4star",
                     map_name: str = "paldea", content: str = "standard",
                     catalog: dict | None = None) -> dict:
    """Resolve a normal/black encounter from its raid seed and game context."""
    if version not in ("scarlet", "violet"):
        raise ValueError(f"unknown game version {version!r}")
    if content not in ("standard", "black"):
        raise ValueError("the bundled seed resolver currently supports standard and black raids")
    data = catalog or load_catalog()
    rand = Xoroshiro128Plus(seed & 0xFFFFFFFF)
    stars = _stars(rand, progress) if content == "standard" else 6
    try:
        total = RATE_TOTALS[(map_name, version)][stars]
        rows = data["encounters"][f"{map_name}_{content}"]
    except KeyError as exc:
        raise ValueError(f"unknown raid map/context {map_name!r}/{content!r}") from exc
    choice = rand.next_int(total)
    for encounter in rows:
        minimum = encounter["rate_min"][version]
        if (encounter["stars"] == stars and minimum >= 0
                and minimum <= choice < minimum + encounter["rate"]):
            return dict(encounter, map=map_name, content=content, version=version,
                        progress=progress, rate_choice=choice)
    raise ValueError(f"no {stars}-star encounter for seed {seed:08X}, roll {choice}/{total}")


def personal_entry(species: int, form: int = 0, *, catalog: dict | None = None) -> dict:
    data = catalog or load_catalog()
    raw = data["personal_sv"]
    count = len(raw) // PERSONAL_SIZE
    if not 0 <= species < count:
        raise ValueError(f"species {species} is outside the SV personal table")
    base = raw[species * PERSONAL_SIZE:(species + 1) * PERSONAL_SIZE]
    form_count = base[0x1A]
    form_index = struct.unpack_from("<H", base, 0x18)[0]
    index = form_index + form - 1 if form and form < form_count and form_index else species
    entry = raw[index * PERSONAL_SIZE:(index + 1) * PERSONAL_SIZE]
    return {
        "base_stats": tuple(entry[:6]),
        "types": tuple(entry[6:8]),
        "gender_ratio": entry[0x0C],
        "base_friendship": entry[0x0E],
        "growth": entry[0x0F],
        "abilities": struct.unpack_from("<3H", entry, 0x12),
    }


def tera_type(seed: int, encounter: dict, *, catalog: dict | None = None) -> int:
    specification = encounter["tera"]
    if specification >= 2:
        return specification - 2
    rand = Xoroshiro128Plus(seed & 0xFFFFFFFF)
    if specification == 1:
        return rand.next_int(18)
    personal = personal_entry(encounter["species"], encounter["form"], catalog=catalog)
    return personal["types"][rand.next_int(2)]


def _reward_count(roll: int, stars: int) -> int:
    column = 0 if roll < 10 else 1 if roll < 40 else 2 if roll < 70 else 3 if roll < 90 else 4
    return REWARD_SLOTS[stars - 1][column]


def _resolve_item(entry: dict, encounter: dict, gem: int, catalog: dict) -> int:
    if entry["item"]:
        return entry["item"]
    if entry["category"] == 1:
        return int(catalog["material_items"].get(str(encounter["species"]), 0))
    if entry["category"] == 2:
        return TERA_SHARDS[gem]
    return 0


def generate_rewards(seed: int, encounter: dict, *, boost: int = 0,
                     catalog: dict | None = None) -> list[dict]:
    """Return the ordered fixed and lottery reward entries for a resolved encounter."""
    data = catalog or load_catalog()
    gem = tera_type(seed, encounter, catalog=data)
    fixed = data["fixed_rewards"][encounter["fixed_rewards"]]
    lottery = data["lottery_rewards"][encounter["lottery_rewards"]]
    result = []

    def append(entry: dict, source: str) -> None:
        item = _resolve_item(entry, encounter, gem, data)
        if item:
            result.append({
                "item": item,
                "name": (data["item_names"][item]
                         if item < len(data["item_names"]) else f"Item {item}"),
                "amount": entry["amount"],
                "subject": entry["subject"],
                "source": source,
            })

    for entry in fixed:
        append(entry, "fixed")
    rand = Xoroshiro128Plus(seed & 0xFFFFFFFF)
    count = _reward_count(rand.next_int(100), encounter["stars"]) + boost
    total = sum(entry["probability"] for entry in lottery)
    for _ in range(count):
        threshold = rand.next_int(total)
        for entry in lottery:
            if entry["probability"] > threshold:
                append(entry, "lottery")
                break
            threshold -= entry["probability"]
    return result


def resolve_raid(seed: int, **context) -> dict:
    data = load_catalog()
    encounter = select_encounter(seed, catalog=data, **context)
    gem = tera_type(seed, encounter, catalog=data)
    species = encounter["species"]
    return {
        "seed": seed & 0xFFFFFFFF,
        "encounter": encounter,
        "species_name": (data["species_names"][species]
                         if species < len(data["species_names"]) else f"Species {species}"),
        "tera_type": gem,
        "rewards": generate_rewards(seed, encounter, catalog=data),
    }
